# SCSS Lint

scss_files: 'scss/**/*.scss'
exclude: 'scss/vendors/**/*'

linters:
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  DeclarationOrder:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  ElsePlacement:
    enabled: false
  ImportantRule:
    enabled: false
  Indentation:
    character: space
    enabled: true
    width: 2
  IdSelector:
    enabled: false
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: true
    max_depth: 4
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: true
    max_depth: 4
  SelectorFormat:
    enabled: false
    convention: strict_BEM
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: true
    style: double_quotes
